name: lg_world_intelligence_map
description: AI-Powered World Intelligence Map for Liquid Galaxy
publish_to: 'none'
version: 1.0.0+1

flutter_native_splash:
  color: "#0F172A"
  image: assets/images/lg_logo.png

  android_12:
    color: "#0F172A"
    image: assets/images/lg_logo.png

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^4.0.2

  flutter_native_splash: ^2.4.7

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Networking
  dio: ^5.8.0+1

  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^1.4.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # SSH & KML
  dartssh2: ^2.10.0
  xml: ^6.5.0

  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17

  #ai
  google_generative_ai: ^0.4.6

  #http
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/lg_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/images/lg_logo.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/lg_logo.png
    - assets/images/lg_splash_screen.png
